// web/sveltekit-marketing/files/src/lib/components/SiteHeader.svelte
<script lang="ts">
  import { SITE_NAME } from "$lib/env";
  import Search from "./Search.svelte";
</script>

<header class="border-b border-zinc-200">
  <div class="mx-auto flex w-full max-w-5xl items-center justify-between px-4 py-4">
    <a href="/" class="font-semibold">{SITE_NAME}</a>
    <div class="flex items-center gap-6">
      <nav class="flex items-center gap-6 text-sm text-zinc-600">
        <a href="/about" class="hover:text-zinc-900">About</a>
        <a href="/contact" class="hover:text-zinc-900">Contact</a>
      </nav>
      <Search />
    </div>
  </div>
</header>

// web/nextjs-marketing/files/src/components/site-header.tsx
import Link from "next/link";
import { Search } from "./Search";

export function SiteHeader() {
  const name = process.env.NEXT_PUBLIC_SITE_NAME ?? "GPP Web";
  return (
    <header className="border-b border-zinc-200">
      <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-4 py-4">
        <Link href="/" className="font-semibold">
          {name}
        </Link>
        <div className="flex items-center gap-6">
          <nav className="flex items-center gap-6 text-sm text-zinc-600">
            <Link href="/about" className="hover:text-zinc-900">
              About
            </Link>
            <Link href="/contact" className="hover:text-zinc-900">
              Contact
            </Link>
          </nav>
          <Search />
        </div>
      </div>
    </header>
  );
}
