// web/sveltekit-headless-strapi/files/src/lib/components/blog/Pagination.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  interface Props {
    currentPage: number;
    pageCount: number;
    basePath?: string;
  }

  let { currentPage, pageCount, basePath = "/blog" }: Props = $props();

  const pages = $derived(
    Array.from({ length: pageCount }, (_, i) => i + 1)
  );
</script>

{#if pageCount > 1}
  <nav class="flex items-center justify-center gap-2" aria-label="Pagination">
    <a
      href={currentPage > 1 ? `${basePath}?page=${currentPage - 1}` : undefined}
      class={cn(
        "px-3 py-2 text-sm font-medium rounded-md transition-colors",
        currentPage > 1
          ? "text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800"
          : "text-gray-400 dark:text-gray-600 cursor-not-allowed"
      )}
      aria-disabled={currentPage <= 1}
    >
      Previous
    </a>

    {#each pages as page}
      <a
        href={`${basePath}?page=${page}`}
        class={cn(
          "px-3 py-2 text-sm font-medium rounded-md transition-colors",
          page === currentPage
            ? "bg-brand-600 text-white"
            : "text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800"
        )}
        aria-current={page === currentPage ? "page" : undefined}
      >
        {page}
      </a>
    {/each}

    <a
      href={currentPage < pageCount ? `${basePath}?page=${currentPage + 1}` : undefined}
      class={cn(
        "px-3 py-2 text-sm font-medium rounded-md transition-colors",
        currentPage < pageCount
          ? "text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800"
          : "text-gray-400 dark:text-gray-600 cursor-not-allowed"
      )}
      aria-disabled={currentPage >= pageCount}
    >
      Next
    </a>
  </nav>
{/if}

// web/nextjs-saas-dashboard/files/src/components/data/pagination.tsx
"use client";

import * as React from "react";
import { ChevronLeft, ChevronRight, MoreHorizontal } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button, buttonVariants } from "@/components/ui/button";

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  className?: string;
}

export function Pagination({
  currentPage,
  totalPages,
  onPageChange,
  className,
}: PaginationProps) {
  const getPageNumbers = () => {
    const pages: (number | "ellipsis")[] = [];
    const showEllipsisStart = currentPage > 3;
    const showEllipsisEnd = currentPage < totalPages - 2;

    if (totalPages <= 7) {
      return Array.from({ length: totalPages }, (_, i) => i + 1);
    }

    pages.push(1);

    if (showEllipsisStart) {
      pages.push("ellipsis");
    }

    const start = Math.max(2, currentPage - 1);
    const end = Math.min(totalPages - 1, currentPage + 1);

    for (let i = start; i <= end; i++) {
      if (!pages.includes(i)) {
        pages.push(i);
      }
    }

    if (showEllipsisEnd) {
      pages.push("ellipsis");
    }

    if (!pages.includes(totalPages)) {
      pages.push(totalPages);
    }

    return pages;
  };

  if (totalPages <= 1) return null;

  return (
    <nav
      role="navigation"
      aria-label="pagination"
      className={cn("flex items-center justify-center gap-1", className)}
    >
      <Button
        variant="outline"
        size="icon"
        onClick={() => onPageChange(currentPage - 1)}
        disabled={currentPage === 1}
        aria-label="Go to previous page"
      >
        <ChevronLeft className="h-4 w-4" />
      </Button>

      {getPageNumbers().map((page, index) =>
        page === "ellipsis" ? (
          <span
            key={`ellipsis-${index}`}
            className="flex h-9 w-9 items-center justify-center"
          >
            <MoreHorizontal className="h-4 w-4" />
          </span>
        ) : (
          <Button
            key={page}
            variant={currentPage === page ? "default" : "outline"}
            size="icon"
            onClick={() => onPageChange(page)}
            aria-label={`Go to page ${page}`}
            aria-current={currentPage === page ? "page" : undefined}
          >
            {page}
          </Button>
        )
      )}

      <Button
        variant="outline"
        size="icon"
        onClick={() => onPageChange(currentPage + 1)}
        disabled={currentPage === totalPages}
        aria-label="Go to next page"
      >
        <ChevronRight className="h-4 w-4" />
      </Button>
    </nav>
  );
}

interface PaginationInfoProps {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  className?: string;
}

export function PaginationInfo({
  currentPage,
  pageSize,
  totalItems,
  className,
}: PaginationInfoProps) {
  const start = (currentPage - 1) * pageSize + 1;
  const end = Math.min(currentPage * pageSize, totalItems);

  return (
    <p className={cn("text-sm text-zinc-500 dark:text-zinc-400", className)}>
      Showing <span className="font-medium">{start}</span> to{" "}
      <span className="font-medium">{end}</span> of{" "}
      <span className="font-medium">{totalItems}</span> results
    </p>
  );
}
