// web/nextjs-saas-dashboard/files/src/components/ui/badge.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const badgeVariants = cva(
  "inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-zinc-950 focus:ring-offset-2 dark:focus:ring-zinc-300",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-zinc-900 text-zinc-50 shadow hover:bg-zinc-900/80 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/80",
        secondary:
          "border-transparent bg-zinc-100 text-zinc-900 hover:bg-zinc-100/80 dark:bg-zinc-800 dark:text-zinc-50 dark:hover:bg-zinc-800/80",
        destructive:
          "border-transparent bg-red-500 text-zinc-50 shadow hover:bg-red-500/80 dark:bg-red-900 dark:text-zinc-50 dark:hover:bg-red-900/80",
        success:
          "border-transparent bg-green-500 text-zinc-50 shadow hover:bg-green-500/80 dark:bg-green-900 dark:text-zinc-50 dark:hover:bg-green-900/80",
        warning:
          "border-transparent bg-yellow-500 text-zinc-900 shadow hover:bg-yellow-500/80 dark:bg-yellow-600 dark:text-zinc-50 dark:hover:bg-yellow-600/80",
        outline: "text-zinc-950 dark:text-zinc-50",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  );
}

export { Badge, badgeVariants };

// web/sveltekit-admin-dashboard/files/src/lib/components/ui/Badge.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { Snippet } from "svelte";

  type Variant = "default" | "success" | "warning" | "error" | "outline";

  interface Props {
    variant?: Variant;
    children: Snippet;
    class?: string;
  }

  let { variant = "default", children, class: className }: Props = $props();

  const variants: Record<Variant, string> = {
    default: "bg-brand-100 text-brand-800 dark:bg-brand-900 dark:text-brand-200",
    success: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
    warning: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
    error: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
    outline: "border border-gray-300 dark:border-gray-600",
  };
</script>

<span
  class={cn(
    "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium",
    variants[variant],
    className
  )}
>
  {@render children()}
</span>
