// web/nextjs-webapp/files/src/app/dashboard/page.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/layout/page-header";

// Example data - replace with your own data source
const stats = [
  { label: "Total Items", value: "1,234", change: "+12%" },
  { label: "Active Users", value: "567", change: "+5%" },
  { label: "Completed", value: "89%", change: "+2%" },
  { label: "Pending", value: "23", change: "-8%" },
];

const recentActivity = [
  { id: 1, action: "Created new item", user: "John", time: "2 min ago" },
  { id: 2, action: "Updated settings", user: "Jane", time: "5 min ago" },
  { id: 3, action: "Exported data", user: "Bob", time: "1 hour ago" },
  { id: 4, action: "Added comment", user: "Alice", time: "2 hours ago" },
];

export default function DashboardPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <PageHeader
        title="Dashboard"
        description="Overview of your application"
        actions={
          <Button>Create New</Button>
        }
      />

      {/* Stats Grid */}
      <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat) => (
          <Card key={stat.label}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">{stat.label}</CardTitle>
              <Badge variant={stat.change.startsWith("+") ? "success" : "secondary"}>
                {stat.change}
              </Badge>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stat.value}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Content Grid */}
      <div className="mt-8 grid gap-6 md:grid-cols-2">
        {/* Recent Activity */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Latest actions in your app</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentActivity.map((item) => (
                <div
                  key={item.id}
                  className="flex items-center justify-between border-b border-zinc-100 pb-3 last:border-0 dark:border-zinc-800"
                >
                  <div>
                    <p className="text-sm font-medium">{item.action}</p>
                    <p className="text-xs text-zinc-500 dark:text-zinc-400">
                      by {item.user}
                    </p>
                  </div>
                  <span className="text-xs text-zinc-500 dark:text-zinc-400">
                    {item.time}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Quick Actions */}
        <Card>
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
            <CardDescription>Common tasks you can perform</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              <Button variant="outline" className="justify-start">
                Create new item
              </Button>
              <Button variant="outline" className="justify-start">
                Import data
              </Button>
              <Button variant="outline" className="justify-start">
                Export report
              </Button>
              <Button variant="outline" className="justify-start">
                View analytics
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// web/sveltekit-webapp/files/src/routes/dashboard/+page.svelte
<script lang="ts">
  import Card from "$lib/components/ui/card.svelte";
  import { TrendingUp, Users, Activity, DollarSign } from "lucide-svelte";

  const stats = [
    { title: "Total Revenue", value: "$45,231.89", change: "+20.1%", icon: DollarSign },
    { title: "Active Users", value: "2,350", change: "+15.2%", icon: Users },
    { title: "Sessions", value: "12,543", change: "+8.4%", icon: Activity },
    { title: "Conversion Rate", value: "3.2%", change: "+4.1%", icon: TrendingUp },
  ];
</script>

<svelte:head>
  <title>Dashboard | GPP Web</title>
</svelte:head>

<div class="space-y-8">
  <div>
    <h1 class="text-3xl font-bold tracking-tight">Dashboard</h1>
    <p class="mt-2 text-muted-foreground">
      Overview of your key metrics and performance.
    </p>
  </div>

  <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
    {#each stats as stat}
      <Card class="p-6">
        <div class="flex items-center justify-between">
          <p class="text-sm font-medium text-muted-foreground">{stat.title}</p>
          <svelte:component this={stat.icon} class="h-4 w-4 text-muted-foreground" />
        </div>
        <div class="mt-2">
          <p class="text-2xl font-bold">{stat.value}</p>
          <p class="text-xs text-green-600">{stat.change} from last month</p>
        </div>
      </Card>
    {/each}
  </div>

  <div class="grid gap-4 lg:grid-cols-2">
    <Card class="p-6">
      <h3 class="font-semibold">Recent Activity</h3>
      <div class="mt-4 space-y-4">
        {#each Array(5) as _, i}
          <div class="flex items-center gap-4">
            <div class="h-2 w-2 rounded-full bg-primary" />
            <div class="flex-1">
              <p class="text-sm">Activity item {i + 1}</p>
              <p class="text-xs text-muted-foreground">2 hours ago</p>
            </div>
          </div>
        {/each}
      </div>
    </Card>

    <Card class="p-6">
      <h3 class="font-semibold">Quick Actions</h3>
      <div class="mt-4 grid gap-2">
        <button class="rounded-lg border p-3 text-left text-sm hover:bg-muted">
          Create new project
        </button>
        <button class="rounded-lg border p-3 text-left text-sm hover:bg-muted">
          Invite team member
        </button>
        <button class="rounded-lg border p-3 text-left text-sm hover:bg-muted">
          Generate report
        </button>
      </div>
    </Card>
  </div>
</div>
