// web/sveltekit-headless-wp-cms/files/src/routes/blog/+page.svelte
<script lang="ts">
  import PostCard from "$lib/components/blog/PostCard.svelte";
  import Pagination from "$lib/components/blog/Pagination.svelte";
  import type { PageData } from "./$types";

  interface Props {
    data: PageData;
  }

  let { data }: Props = $props();
</script>

<svelte:head>
  <title>Blog | My Blog</title>
  <meta name="description" content="Read our latest posts and insights" />
</svelte:head>

<section class="py-16">
  <div class="container mx-auto px-4">
    <div class="mb-12">
      <h1 class="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-4">
        Blog
      </h1>
      <p class="text-gray-600 dark:text-gray-400">
        Explore our latest posts, tutorials, and insights.
      </p>
    </div>

    {#if data.categories.length > 0}
      <div class="flex flex-wrap gap-2 mb-8">
        <a
          href="/blog"
          class="px-4 py-2 text-sm font-medium rounded-full transition-colors bg-brand-600 text-white"
        >
          All
        </a>
        {#each data.categories as category}
          <a
            href="/category/{category.slug}"
            class="px-4 py-2 text-sm font-medium rounded-full transition-colors bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700"
          >
            {category.name}
          </a>
        {/each}
      </div>
    {/if}

    {#if data.posts.length > 0}
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {#each data.posts as post}
          <PostCard {post} />
        {/each}
      </div>

      <div class="mt-12">
        <Pagination
          hasNextPage={data.pageInfo.hasNextPage}
          hasPreviousPage={data.pageInfo.hasPreviousPage}
          currentCursor={data.pageInfo.endCursor}
        />
      </div>
    {:else}
      <div class="text-center py-12">
        <p class="text-gray-600 dark:text-gray-400">
          No posts found.
        </p>
      </div>
    {/if}
  </div>
</section>

// web/nextjs-headless-wp-full/files/src/app/blog/page.tsx
import Link from 'next/link'
import Image from 'next/image'
import { Calendar, User } from 'lucide-react'
import { getPosts, getCategories, formatPostDate } from '@/lib/posts'
import type { Post, PostCategory } from '@/lib/graphql'

export const metadata = {
  title: 'Blog',
  description: 'Latest blog posts and articles',
}

export default async function BlogPage() {
  const [postsData, categories] = await Promise.all([
    getPosts({ first: 12 }),
    getCategories(),
  ])

  const posts = postsData.posts.nodes
  const primaryCategories = categories.filter(cat => !cat.parent?.node)

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Header */}
      <div className="mb-12">
        <h1 className="text-4xl font-bold mb-4">Blog</h1>
        <p className="text-lg text-muted-foreground">
          Explore our content by category
        </p>
      </div>

      {/* Categories */}
      {primaryCategories.length > 0 && (
        <div className="mb-12">
          <h2 className="text-2xl font-semibold mb-6">Categories</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {primaryCategories.map((category) => (
              <Link
                key={category.id}
                href={`/blog/${category.slug}`}
                className="rounded-lg border bg-card p-6 transition hover:border-primary hover:shadow-md"
              >
                <h3 className="text-lg font-semibold mb-2">{category.name}</h3>
                {category.description && (
                  <p className="text-sm text-muted-foreground line-clamp-2">
                    {category.description}
                  </p>
                )}
                {category.count !== undefined && (
                  <p className="mt-2 text-xs text-muted-foreground">
                    {category.count} {category.count === 1 ? 'post' : 'posts'}
                  </p>
                )}
              </Link>
            ))}
          </div>
        </div>
      )}

      {/* Recent Posts */}
      <div>
        <h2 className="text-2xl font-semibold mb-6">Recent Posts</h2>
        {posts.length > 0 ? (
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            {posts.map((post) => (
              <article
                key={post.id}
                className="rounded-lg border bg-card transition hover:shadow-lg"
              >
                {post.featuredImage?.node?.sourceUrl && (
                  <Link href={`/blog/${post.slug}`}>
                    <Image
                      src={post.featuredImage.node.sourceUrl}
                      alt={post.featuredImage.node.altText || post.title}
                      width={400}
                      height={250}
                      className="w-full h-48 object-cover rounded-t-lg"
                    />
                  </Link>
                )}
                <div className="p-6">
                  <div className="mb-2 flex flex-wrap gap-2">
                    {post.categories?.nodes.map((category) => {
                      const catParent = category.parent?.node
                      const catPath = catParent
                        ? `/blog/${catParent.slug}/${category.slug}`
                        : `/blog/${category.slug}`
                      return (
                        <Link
                          key={category.id}
                          href={catPath}
                          className="text-xs font-medium text-primary hover:text-primary/80"
                        >
                          {category.name}
                        </Link>
                      )
                    })}
                  </div>
                  <Link href={`/blog/${post.slug}`}>
                    <h3 className="text-xl font-semibold mb-2 hover:text-primary">
                      {post.title}
                    </h3>
                  </Link>
                  {post.excerpt && (
                    <p className="mb-4 text-sm text-muted-foreground line-clamp-3">
                      {post.excerpt.replace(/<[^>]*>/g, '').substring(0, 150)}...
                    </p>
                  )}
                  <div className="flex items-center justify-between text-xs text-muted-foreground">
                    <time dateTime={post.date}>
                      {formatPostDate(post.date)}
                    </time>
                    {post.author?.node?.name && (
                      <span>By {post.author.node.name}</span>
                    )}
                  </div>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <p className="text-muted-foreground">
            No posts yet. Check back soon!
          </p>
        )}
      </div>
    </div>
  )
}
