// web/nextjs-marketing/files/src/app/terms/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using our service",
};

export default function TermsPage() {
  const lastUpdated = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="text-sm text-zinc-500 mt-2">Last updated: {lastUpdated}</p>
      </div>
      
      <div className="prose prose-zinc max-w-none">
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">Acceptance of Terms</h2>
          <p className="text-zinc-600">
            By accessing and using this website, you accept and agree to be bound
            by the terms and provision of this agreement.
          </p>
        </section>
        
        <section className="space-y-4 mt-8">
          <h2 className="text-2xl font-semibold">Use License</h2>
          <p className="text-zinc-600">
            Permission is granted to temporarily access the materials on this
            website for personal, non-commercial transitory viewing only.
          </p>
        </section>
        
        <section className="space-y-4 mt-8">
          <h2 className="text-2xl font-semibold">User Accounts</h2>
          <p className="text-zinc-600">
            You are responsible for maintaining the confidentiality of your account
            and password and for restricting access to your computer.
          </p>
        </section>
        
        <section className="space-y-4 mt-8">
          <h2 className="text-2xl font-semibold">Prohibited Uses</h2>
          <p className="text-zinc-600">
            You may not use our service for any unlawful purpose or to solicit
            others to perform unlawful acts.
          </p>
        </section>
        
        <section className="space-y-4 mt-8">
          <h2 className="text-2xl font-semibold">Limitation of Liability</h2>
          <p className="text-zinc-600">
            In no event shall we be liable for any damages arising out of the use
            or inability to use the materials on this website.
          </p>
        </section>
        
        <section className="space-y-4 mt-8">
          <h2 className="text-2xl font-semibold">Changes to Terms</h2>
          <p className="text-zinc-600">
            We reserve the right to revise these terms at any time without notice.
            By using this website, you are agreeing to be bound by the current
            version of these terms.
          </p>
        </section>
        
        <section className="space-y-4 mt-8">
          <h2 className="text-2xl font-semibold">Contact Information</h2>
          <p className="text-zinc-600">
            If you have any questions about these Terms of Service, please contact
            us through our <a href="/contact" className="text-blue-600 hover:underline">contact page</a>.
          </p>
        </section>
      </div>
    </div>
  );
}

// web/sveltekit-marketing/files/src/routes/terms/+page.svelte
<script lang="ts">
  import { SITE_NAME } from "$lib/env";
</script>

<svelte:head>
  <title>Terms of Service | {SITE_NAME}</title>
  <meta name="description" content="Terms of service for {SITE_NAME}" />
</svelte:head>

<div class="space-y-6">
  <h1 class="text-3xl font-semibold tracking-tight">Terms of Service</h1>

  <p class="text-sm text-zinc-500">Last updated: {new Date().toLocaleDateString()}</p>

  <div class="prose prose-zinc max-w-none space-y-6">
    <section>
      <h2 class="text-xl font-medium">1. Acceptance of Terms</h2>
      <p class="text-zinc-600">
        By accessing and using this website, you accept and agree to be bound by the terms
        and provision of this agreement.
      </p>
    </section>

    <section>
      <h2 class="text-xl font-medium">2. Use License</h2>
      <p class="text-zinc-600">
        Permission is granted to temporarily access the materials on this website for personal,
        non-commercial transitory viewing only.
      </p>
    </section>

    <section>
      <h2 class="text-xl font-medium">3. Disclaimer</h2>
      <p class="text-zinc-600">
        The materials on this website are provided on an 'as is' basis. We make no warranties,
        expressed or implied, and hereby disclaim and negate all other warranties.
      </p>
    </section>

    <section>
      <h2 class="text-xl font-medium">4. Limitations</h2>
      <p class="text-zinc-600">
        In no event shall we or our suppliers be liable for any damages arising out of the use
        or inability to use the materials on this website.
      </p>
    </section>

    <section>
      <h2 class="text-xl font-medium">5. Governing Law</h2>
      <p class="text-zinc-600">
        These terms and conditions are governed by and construed in accordance with applicable laws,
        and you irrevocably submit to the exclusive jurisdiction of the courts in that location.
      </p>
    </section>
  </div>
</div>
