// web/nextjs-webapp/files/src/app/dashboard/page.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/layout/page-header";

// Example data - replace with your own data source
const stats = [
  { label: "Total Items", value: "1,234", change: "+12%" },
  { label: "Active Users", value: "567", change: "+5%" },
  { label: "Completed", value: "89%", change: "+2%" },
  { label: "Pending", value: "23", change: "-8%" },
];

const recentActivity = [
  { id: 1, action: "Created new item", user: "John", time: "2 min ago" },
  { id: 2, action: "Updated settings", user: "Jane", time: "5 min ago" },
  { id: 3, action: "Exported data", user: "Bob", time: "1 hour ago" },
  { id: 4, action: "Added comment", user: "Alice", time: "2 hours ago" },
];

export default function DashboardPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <PageHeader
        title="Dashboard"
        description="Overview of your application"
        actions={
          <Button>Create New</Button>
        }
      />

      {/* Stats Grid */}
      <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat) => (
          <Card key={stat.label}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">{stat.label}</CardTitle>
              <Badge variant={stat.change.startsWith("+") ? "success" : "secondary"}>
                {stat.change}
              </Badge>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stat.value}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Content Grid */}
      <div className="mt-8 grid gap-6 md:grid-cols-2">
        {/* Recent Activity */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Latest actions in your app</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {recentActivity.map((item) => (
                <div
                  key={item.id}
                  className="flex items-center justify-between border-b border-zinc-100 pb-3 last:border-0 dark:border-zinc-800"
                >
                  <div>
                    <p className="text-sm font-medium">{item.action}</p>
                    <p className="text-xs text-zinc-500 dark:text-zinc-400">
                      by {item.user}
                    </p>
                  </div>
                  <span className="text-xs text-zinc-500 dark:text-zinc-400">
                    {item.time}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Quick Actions */}
        <Card>
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
            <CardDescription>Common tasks you can perform</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              <Button variant="outline" className="justify-start">
                Create new item
              </Button>
              <Button variant="outline" className="justify-start">
                Import data
              </Button>
              <Button variant="outline" className="justify-start">
                Export report
              </Button>
              <Button variant="outline" className="justify-start">
                View analytics
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// web/sveltekit-saas-dashboard/files/src/routes/(app)/dashboard/+page.svelte
<script lang="ts">
  import StatsCard from "$lib/components/data/StatsCard.svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import { user } from "$lib/stores/auth";

  const stats = [
    { title: "Total Projects", value: 12, change: 8.2, icon: "projects" as const },
    { title: "Team Members", value: 8, change: 12.5, icon: "users" as const },
    { title: "Active Users", value: 1234, change: 4.3, icon: "growth" as const },
    { title: "Revenue", value: "$12,450", change: 15.8, icon: "revenue" as const },
  ];

  const recentActivity = [
    { action: "New user signed up", time: "5 minutes ago", type: "success" },
    { action: "Project 'Website Redesign' completed", time: "2 hours ago", type: "info" },
    { action: "Invoice #1234 paid", time: "4 hours ago", type: "success" },
    { action: "Team member added", time: "1 day ago", type: "info" },
    { action: "New project created", time: "2 days ago", type: "info" },
  ];
</script>

<svelte:head>
  <title>Dashboard - SaaS App</title>
</svelte:head>

<div class="space-y-6">
  <div>
    <h1 class="text-2xl font-bold">Welcome back, {$user?.name}!</h1>
    <p class="text-gray-500 dark:text-gray-400 mt-1">Here's what's happening with your projects today.</p>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    {#each stats as stat}
      <StatsCard {...stat} />
    {/each}
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <Card class="p-6">
      <h2 class="text-lg font-semibold mb-4">Recent Activity</h2>
      <div class="space-y-4">
        {#each recentActivity as activity}
          <div class="flex items-start gap-3">
            <div class="w-2 h-2 rounded-full mt-2 {activity.type === 'success' ? 'bg-green-500' : 'bg-blue-500'}"></div>
            <div>
              <p class="text-sm">{activity.action}</p>
              <p class="text-xs text-gray-500 dark:text-gray-400">{activity.time}</p>
            </div>
          </div>
        {/each}
      </div>
    </Card>

    <Card class="p-6">
      <h2 class="text-lg font-semibold mb-4">Quick Actions</h2>
      <div class="grid grid-cols-2 gap-4">
        <a
          href="/projects"
          class="p-4 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          <svg class="w-6 h-6 text-brand-500 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
          <p class="font-medium text-sm">New Project</p>
        </a>
        <a
          href="/admin/team"
          class="p-4 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          <svg class="w-6 h-6 text-brand-500 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
          </svg>
          <p class="font-medium text-sm">Invite Team</p>
        </a>
        <a
          href="/analytics"
          class="p-4 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          <svg class="w-6 h-6 text-brand-500 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
          </svg>
          <p class="font-medium text-sm">View Analytics</p>
        </a>
        <a
          href="/settings"
          class="p-4 rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          <svg class="w-6 h-6 text-brand-500 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          <p class="font-medium text-sm">Settings</p>
        </a>
      </div>
    </Card>
  </div>
</div>
